//! SeaORM Entity. Generated by hand matching AnkiTov standards.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "generation_jobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,                 // UUID
    pub status: String,             // "pending", "processing", "completed", "failed"
    pub progress: i32,              // 0 to 100
    pub total_students: i32,
    pub completed_students: i32,
    pub anomalies: Option<String>,  // JSON serialized warning logs
    pub completed_at: Option<i64>,  // UNIX timestamp
    pub created_at: i64,            // UNIX timestamp
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
