//! SeaORM Entity. Generated by hand matching AnkiTov standards.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "profile_assignments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub target_type: String,        // "student" or "cohort"
    pub target_id: String,          // user.id or subsection_id
    pub track_profile_id: String,
    pub priority: i32,              // lower = higher priority (default: 1 student, 10 cohort)
    pub assigned_by: String,
    pub assigned_at: i64,           // UNIX timestamp
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
